runtime: php82
env: standard
runtime_config:
  document_root: public

entrypoint: serve public/index.php

automatic_scaling:
  max_instances: 1
env_variables:
  VIEW_COMPILED_PATH: /tmp
  LOG_CHANNEL: stderr
  LOG_FILE: /tmp/laravel.log
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: base64:AubOzgN5IG5W4AQ3u9njqpni7Eoyv+SS6J48R4674bs=
  CACHE_DRIVER: file
  SESSION_DRIVER: database
  APP_LOG: daily
  APP_TIMEZONE: UTC

  DB_CONNECTION: mysql
  #  DB_HOST: localhost
  DB_DATABASE: inote_database
  DB_USERNAME: root
  DB_PASSWORD: qwiklabs-gcp-00-b5d5912cd172
  DB_SOCKET: "/cloudsql/qwiklabs-gcp-00-b5d5912cd172:us-east1:myinstance"

  QUEUE_CONNECTION: database
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.sparkpostmail.com
  MAIL_PORT: 587
  MAIL_USERNAME: sparkpost_username
  MAIL_PASSWORD: password
  LOG_DELETE: true
  GOOGLE_VISION_PROJECT_ID: project_id
beta_settings:
  cloud_sql_instances: qwiklabs-gcp-00-b5d5912cd172:us-east1:myinstance
